# Generated by Django 5.1 on 2026-01-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_pledge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='anonymouns',
            new_name='anonymous',
        ),
    ]
